### ISSUE TITLE
Getting an error and this is the fix -  experimental.asyncContext: true... 

### ISSUE THREAD

**Issue by aaronksaunders** [wobsoriano/nuxt-remote-fn#9]
I followed the instructions and it works fine now. I searched the repo for this setting and could not find it anywhere. Not sure if I missed something in the doc or if my versions are off.

## package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "HOST=0.0.0.0 nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "0.8.3",
    "@types/node": "^18.17.3",
    "nuxt": "3.7.1"
  },
  "dependencies": {
    "@trpc/client": "^10.38.1",
    "@trpc/server": "^10.38.1",
    "nuxt-remote-fn": "^0.4.1",
    "trpc-nuxt": "^0.10.12",
    "zod": "^3.22.2"
  }
}
```

## Error
```
{
    "url": "/api/__remote/greeting/getAllTodos",
    "statusCode": 500,
    "statusMessage": "",
    "message": "Nitro request context is not available. Enable the experimental flag using `experimental.asyncContext: true`.",
    "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/h3/dist/index.mjs:78:15)</span>\n<span class=\"stack internal\">at useEvent (./node_modules/nitropack/dist/runtime/context.mjs:13:11)</span>\n<span class=\"stack\">at H3Event.createContext$1 (./lib/greeting.server.ts:11:1)</span>\n<span class=\"stack internal\">at <anonymous> (./node_modules/nuxt-remote-fn/dist/runtime/server.mjs:25:50)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)</span></pre>"
}
```

**Comment by wobsoriano** [comment]
Thanks for reporting! I published a new version, `useEvent` is now `useH3Event`.

Nitro now has a [useEvent](https://unjs.io/blog/2023-08-25-nitro-2.6#async-context-and-composition-api) API that causes the error you're getting.

**Comment by aaronksaunders** [comment]
`useH3Event` doesnt appear to be exported from anywhere

**Comment by wobsoriano** [comment]
Should be from nuxt-remote-fn/server

**Comment by wobsoriano** [comment]
Closing this one, feel free to reopen! Thank you.
